AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  Template to create the Child Account Roles.

Parameters:

  CentralAwsAccountId:
    Description: The AWS account ID of the shared services account.
    Type: String
    AllowedPattern: (\d{12}|^$)
    ConstraintDescription: must be an AWS account ID

Resources:
  ##############################
  # IAM Roles
  ##############################
  ChildAccountFormationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ChildAccountFormationRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref CentralAwsAccountId
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: FormationRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                  - s3:PutObject
                  - s3:GetObject
                  - iam:PassRole
                  - kms:Encrypt
                  - kms:Decrypt
                  - kms:ReEncrypt*
                  - kms:GenerateDataKey*
                  - kms:DescribeKey
                Resource: "*"

  ChildAccountDeployerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ChildAccountDeployerRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: DeployerRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - apigateway:*
                  - cloudformation:*
                  - s3:GetObject
                Resource: "*"